### ISSUE TITLE
Create content for BPMN events

### ISSUE THREAD

**Issue by oguzeroglu** [bpmn-io/docs.bpmn.io#17]
Child of #19 

We should create content for following pages:

 - [x] [saveXML-start.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/saveXML-start.md)
 - [x] [saveSVG-start.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/saveSVG-start.md)
 - [x] [saveXML-done.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/saveXML-done.md)
 - [x] [saveXML-serialized.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/saveXML-serialized.md)
 - [x] [import-parse-start.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/import-parse-start.md)
 - [x] [saveSVG-done.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/saveSVG-done.md)
 - [x] [import-parse-complete.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/import-parse-complete.md)
 - [x] [import-render-start.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/import-render-start.md)
 - [x] [import-render-complete.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/import-render-complete.md)
 - [x] [import-done.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/import-done.md)
 - [x] [moddleCopy-canCopyProperty.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/moddleCopy-canCopyProperty.md)
 - [x] [moddleCopy-canSetCopiedProperty.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/moddleCopy-canSetCopiedProperty.md)
 - [x] [moddleCopy-canCopyProperties.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/moddleCopy-canCopyProperties.md)
 - [x] [bpmnElement-added.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/bpmnElement-added.md)
 - [x] [detach.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/detach.md)
 - [x] [attach.md](https://github.com/bpmn-io/docs.bpmn.io/blob/master/docs/Events/bpmn-events/attach.md)

**Comment by oguzeroglu** [comment]
Reference content: https://bpmn-io.github.io/docs.bpmn.io/events/bpmn-events/import-parse-start

**Comment by MaxTru** [comment]
Example: https://bpmn-io.github.io/docs.bpmn.io/events/bpmn-events/import-parse-start
