### ISSUE TITLE
Consider alternatives for top-level structure

### ISSUE THREAD

**Issue by oguzeroglu** [bpmn-io/docs.bpmn.io#26]
__What should we do?__

We should discuss if it makes sense to split the documentation per toolkit (bpmn-js/dmn-js etc.) rather than components (modules, events etc.)

__Why should we do it?__

Better experience for users and developers.

**Comment by philippfromme** [comment]
Regarding the structure of the documentation my idea is something along these lines:

## Example 1: bpmn-js selected

* Introduction
	* modules
	* commands
	* events
* Reference
	* BpmnJS (e.g. #clear, #destroy, #importXML, #saveXML)
		* EventBus (e.g. #on, #off)
		* Canvas (e.g. #getRootElement, #zoom)
		* Modeling (e.g. #createShape, #updateProperties)
		* BpmnReplace (e.g. #replaceElement)
* Examples

## Example 2: diagram-js selected

* Introduction
	* modules
	* commands
	* events
* Reference
	* Diagram (e.g. #clear, #destroy)
		* EventBus (e.g. #on, #off)
		* Canvas (e.g. #getRootElement, #zoom)
		* Modeling (e.g. #createShape)
		* Replace (e.g. #replaceElement)
* Examples

You'd avoid confusion by selecting the toolkit first and then seeing only the documentation that's relevant for the chosen toolkit. Choose diagram-js, see all diagram-js-related docs, choose bpmn-js, see all diagram-js-related _and_ bpmn-js-related docs.

Copied from https://github.com/bpmn-io/docs.bpmn.io/pull/8#issuecomment-693366907

**Comment by philippfromme** [comment]
My suggestion might be challenging to implement using a single Jekyll website. One alternative would be to generate more than one website from the same sources. So `docs.bpmn.io/diagram-js` would lead to a different page than `docs.bpmn.io/bpmn-js`, similar to how we handle different toolkits on `demo.bpmn.io`.
