### ISSUE TITLE
Look for an alternative to fetch example pages directly from existing examples repository

### ISSUE THREAD

**Issue by oguzeroglu** [bpmn-io/docs.bpmn.io#27]
__What should we do?__

We should look for a way to automatically generate the pages for examples via the existing README.md files of example repository. This Jekyll plugin may be useful: https://github.com/Rolinh/jekyll-remote-markdown (if it's possible to use this plugin with Just-The-Docs + Github Pages)

__Why should we do it?__

In order not to duplicate the content.

**Comment by MaxTru** [comment]
Since we will do https://github.com/bpmn-io/docs.bpmn.io/issues/39, we can close this
