### ISSUE TITLE
Consistently name "usage example"

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/docs.bpmn.io#33]
When providing code examples, we use different terms. The overall wording shall be harmonized:
Examples:
https://bpmn-io.github.io/docs.bpmn.io/modules/bpmn-modules/modeling => `Usage`
https://bpmn-io.github.io/docs.bpmn.io/general/api-reference/bpmn-js/importXML => `Code Example`
https://bpmn-io.github.io/docs.bpmn.io/events/bpmn-events/saveXML-done => `Example Usage`

**Comment by oguzeroglu** [comment]
I converted the rest to `Example Usage` via fb8d1ff
