### ISSUE TITLE
Consistently use bullet points for data elements (or not)

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/docs.bpmn.io#34]
We should consistently use bullet points for data elements (or not).

Example:
https://bpmn-io.github.io/docs.bpmn.io/general/api-reference/bpmn-js/importXML => parameters and return value are given with Bullet points
https://bpmn-io.github.io/docs.bpmn.io/events/bpmn-events/saveXML-done => The data sub-heading listing the attributes is given without bullets.

Can we please have a clear guideline?

**Comment by oguzeroglu** [comment]
I aligned the usage of bullet points via 447176c
